<a href="https://colab.research.google.com/github/rgomesa2025/MVP_MACHINE_LEARNING_E_ANALYTICS/blob/main/notebook/Producao_Nacional_Petroleo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MVP — Machine Learning & Analytics

**PUC-RIO** - Pós-Graduação em Ciência de Dados e Analytics

**Nome:** _Rosângela Gomes André_

**Matrícula:** _4052025002132_

**Data:** _05/07/2026_

**Dataset:** _[Produção de Petróleo e gás natural (ANP)](https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-estatisticos) / [Produção por Poços](https://cdp.anp.gov.br/ords/r/cdp_apex/consulta-dados-publicos-cdp/consulta-produ%C3%A7%C3%A3o-por-po%C3%A7o)_

**Tipo de problema:** _Séries Temporais_ / _forecasting com abordagem supervisionada de regressão_

# 1. Definição do Problema

## 1.1 Descrição do Problema
A indústria de petróleo e gás gera um volume massivo de dados operacionais e séries históricas mensais sobre a extração de recursos. No Brasil, a ANP (Agência Nacional do Petróleo, Gás Natural e Biocombustíveis) disponibiliza publicamente esses dados em nível de poço, contendo volumes de produção (óleo, condensado, gás, água e outras informações técnicas), identificação do campo, bacia, operador e período de referência.

Embora a base original seja granular por poço, **este MVP realiza a consolidação e previsão no nível campo-mês**. Esta abordagem técnica mitiga ruídos e oscilações severas típicas de poços individuais — como paradas operacionais temporárias, manutenções e intervenções, resultando em séries históricas mais estáveis, menos ruidosas e adequadas para o planejamento analítico e estratégico.

## 1.1.1 O Problema e Desafio de Modelagem
A produção de um campo pode variar por maturidade do reservatório, declínio natural, entrada de novos poços, parada de poços existentes, intervenções operacionais, mudança de estratégia de produção e restrições de infraestrutura. Parte desses fatores não está explicitamente disponível nos dados públicos, mas seus efeitos e padrões comportamentais podem aparecer indiretamente nas séries históricas de produção.

O problema central deste MVP é prever a produção mensal de óleo de um campo a partir do histórico observado nos meses anteriores. A solução não pretende substituir modelos complexos de engenharia de reservatórios nem previsões oficiais de produção. O objetivo principal é demonstrar um fluxo completo, reprodutível e criticamente avaliado de Machine Learning aplicado a uma base pública real da indústria.

## 1.2 Objetivo do MVP

O objetivo principal deste MVP é construir, avaliar e comparar modelos de Machine Learning capazes de prever a produção mensal de óleo por campo para os próximos **5 anos (60 meses)**, integrando variáveis de gás como atributos alvos secundários para projetar o comportamento simultâneo das curvas de hidrocarbonetos. A modelagem utilizará o histórico de dados públicos da ANP originalmente coletados por poço e consolidados no nível campo-mês.

Para alcançar esse objetivo de forma rigorosa e criticamente avaliada, o projeto compreende as seguintes etapas específicas:

* **Consolidação Multivariada de Dados:** Tratar e agregar a base histórica da ANP do nível de poço para o nível estável de campo-mês, estruturando as séries temporais das variáveis de **Óleo** (alvo principal), **Óleo Condensado**, **Gás Natural**, **Gás Associado** e **Gás Não Associado** (alvos secundários).
* **Modelagem Preditiva Multi-Output:** Desenvolver e treinar modelos candidatos de Machine Learning estruturados para capturar a interdependência entre as curvas e projetar os volumes acumulados para o horizonte de 5 anos.
* **Avaliação de Desempenho:** Comparar os modelos preditivos desenvolvidos contra abordagens de referência (*baselines* temporais simples), mensurando a acurácia de forma combinada e individual em dados não utilizados no treinamento (dados não vistos).
* **Análise Crítica:** Identificar e discutir as limitações técnicas e práticas da abordagem, avaliando criticamente como a ausência de variáveis físicas, geológicas e operacionais (não disponíveis nos dados públicos) limita o modelo de Machine Learning puro, distinguindo sua aplicação analítica de curto/médio prazo das abordagens físicas tradicionais da engenharia de reservatórios.

## 1.3 Tipo de Problema

**Tipo Escolhido:** Previsão de Séries Temporais (*Time Series Forecasting*) estruturada como Regressão Supervisionada Tabular (Multi-Output).

**Justificativa:**
O projeto lida com a previsão de valores numéricos contínuos (volumes mensais de produção de hidrocarbonetos) distribuídos ao longo do tempo, onde a ordem cronológica dos dados é fundamental para o aprendizado do modelo. O comportamento futuro das curvas depende diretamente do histórico temporal anterior e de sua dinâmica de declínio.

Para viabilizar a aplicação de algoritmos clássicos e avançados de Machine Learning neste MVP, a dimensão temporal será tratada por meio da transformação das séries históricas em uma estrutura tabular supervisionada. Isso será feito através da engenharia de atributos (*feature engineering*), utilizando:
* **Defasagens (*Lags*):** Valores de produção de meses anteriores.
* **Janelas Deslizantes:** Médias móveis e métricas estatísticas acumuladas que capturam a tendência de declínio do campo.
* **Atributos de Calendário/Sazonalidade:** Variáveis que mapeiam o comportamento temporal e padrões cíclicos.
* **Atributos Estáticos do Campo:** Identificação do ativo, bacia e operador.

**Premissas de Validação:**
Por se tratar de um problema estritamente temporal, o ordenamento cronológico dos dados será rigorosamente respeitado na separação entre os conjuntos de treinamento, validação e teste. Serão evitadas técnicas tradicionais de embaralhamento (*shuffle* ou *K-Fold* padrão), adotando-se uma divisão temporal (como *Time Series Split*). Essa estratégia impede o vazamento de dados (*data leakage*) do futuro para o passado e garante que os modelos candidatos sejam avaliados de forma justa em períodos futuros não vistos durante o treinamento, simulando com realismo a projeção do horizonte de 5 anos.

## 1.4 Premissas, Hipóteses e Critérios de Sucesso

### 1. Premissas do Projeto
* **Suficiência dos Dados Públicos:** Os dados históricos disponibilizados publicamente pela ANP possuem os atributos e o volume necessários para a construção de um MVP analítico e exploratório.
* **Redução de Ruído por Agregação:** A consolidação dos dados originais de poço para o nível campo-mês atenua significativamente as oscilações operacionais extremas de poços individuais, criando uma série temporal mais estável e tratável para modelagem.
* **Sinal Histórico Parcial:** A produção histórica agregada carrega sinais intrínsecos de tendência, ciclicidade e curvas de declínio natural que podem ser parcialmente capturados por algoritmos supervisionados.
* **Limitação Informacional Reconhecida:** Eventos operacionais críticos (como decisões comerciais das operadoras, restrições físicas de plataformas ou intervenções planejadas em poços) não estão disponíveis nos dados públicos e impõem um limite natural à acurácia do modelo.

### 2. Hipóteses Iniciais
* **Suficiência Preditiva Temporal:** As variáveis defasadas (*lags*), médias móveis e atributos de sazonalidade derivados da própria série histórica são preditores eficazes para projetar a tendência de comportamento futuro.
* **Correlação Multivariável:** Existe uma forte interdependência entre a curva de Óleo (alvo principal) e as demais curvas de hidrocarbonetos (alvos secundários, como o gás associado e condensado), permitindo que modelos estruturados capturem dinâmicas conjuntas de produção de forma mais consistente do que projeções isoladas.
* **Superioridade do Machine Learning:** Modelos supervisionados não lineares baseados em árvores (como XGBoost ou LightGBM) adaptados para o contexto temporal superarão as abordagens de referência (*baselines* estatísticos simples) ao longo do horizonte de 5 anos projetados.

### 3. Critérios de Sucesso

| Critério | Definição |
| :--- | :--- |
| **Métrica Principal** | **WAPE / WMAPE (Erro Percentual Absoluto Ponderado):**<br><br>• Adotado por ser estatisticamente robusto para séries temporais que contêm valores zerados, evitando divisões por zero.<br>• Pondera o erro proporcionalmente ao volume de produção de cada campo, refletindo o real impacto logístico e financeiro para o planejamento de longo prazo. |
| **Métricas Complementares** | **MAE (Erro Absoluto Médio):** Para monitorar o erro médio absoluto na unidade física (barris/dia).<br><br>**RMSE (Raiz do Erro Quadrático Médio):** Aplicado para penalizar com maior rigor grandes desvios e erros severos de previsão nas curvas de produção. |
| **Resultado Mínimo Esperado** | Superar o melhor *baseline* temporal simples (como o modelo de persistência ou média móvel), obtendo uma **redução de pelo menos 10% a 15% no valor do WAPE** global no conjunto de teste. |
| **Restrição Metodológica** | Respeitar rigorosamente a divisão cronológica dos dados (validação temporal), sem qualquer tipo de embaralhamento (*shuffle* aleatório) para garantir uma avaliação realista e evitar vazamento de dados (*data leakage*). |
| **Restrição Prática** | O pipeline completo deve ser leve, reprodutível e executável no ambiente padrão do **Google Colab**, sem depender de uploads manuais complexos ou infraestrutura de nuvem de alto custo. |
| **Restrição de Uso** | O resultado gerado pelo modelo deve ser interpretado estritamente como uma **projeção analítica exploratória acadêmica**, não possuindo caráter de previsão oficial ou substituição da engenharia de reservatórios. |

## 2. Ambiente, Bibliotecas e Reprodutibilidade

Esta seção reúne o ecossistema de software, pacotes e as configurações de semente (*seed*) necessárias para garantir que a execução deste notebook produza exatamente os mesmos resultados em qualquer ambiente compatível, priorizando a execução nativa no Google Colab.

### Estrutura de Armazenamento e Carga de Dados
Para garantir a máxima reprodutibilidade e eliminar a necessidade de uploads manuais ou configurações locais, **o dataset completo foi centralizado e disponibilizado no repositório público do GitHub**:
* **Repositório:** [rgomesa2025/MVP_MACHINE_LEARNING_E_ANALYTICS](https://github.com/rgomesa2025/MVP_MACHINE_LEARNING_E_ANALYTICS/tree/main/data)

A base histórica apresenta um desafio de padronização estrutural (*data wrangling*): alguns anos estão consolidados em um único arquivo `.csv`, enquanto outros estão fragmentados em arquivos `.csv` mensais dentro da pasta `/data`. Além disso, os formatos e disposições das colunas variam sutilmente entre os anos. No entanto, o pipeline foi projetado para mapear, unificar e ler esses arquivos diretamente da URL pública, extraindo as colunas essenciais (comuns a todos os períodos) durante a etapa de ingestão para garantir a integridade da série temporal.

### Bibliotecas Utilizadas
O pipeline foi desenvolvido utilizando a linguagem Python, apoiando-se nos seguintes blocos de pacotes:

* **Conexão e Requisição de Dados:** `requests` (para comunicação assíncrona e validação do download dos arquivos `.csv` brutos armazenados no GitHub).
* **Manipulação, Ingestão e Padronização:** `pandas` (essencial para ler os arquivos via URL *raw*, mapear colunas divergentes, concatenar os arquivos anuais/mensais e realizar a agregação final no nível campo-mês) e `numpy` (para suporte matemático).
* **Visualização de Dados:** `matplotlib` (essencial para plotar as curvas de declínio e as projeções futuras de 5 anos).
* **Modelagem Preditiva e Machine Learning:** `scikit-learn` (utilizado para divisão temporal via `TimeSeriesSplit`, pré-processamento blindado contra vazamento de dados via `Pipeline`, modelos de referência e algoritmos candidatos como `RandomForestRegressor` e `HistGradientBoostingRegressor`).

In [3]:
# === Setup Básico e Reprodutibilidade ===
import os
import re
import io
import sys
import time
import math
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import sklearn

# Pré-processamento, Validação e Pipelines do Scikit-Learn
from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Modelos (Baseline e Candidatos Avançados)
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor

# Métricas de Avaliação e Scorer customizado para o WAPE
from sklearn.metrics import mean_absolute_error, mean_squared_error, make_scorer

# Ignorar avisos/warnings para limpar o output do notebook
warnings.filterwarnings("ignore")

# Configuração de semente fixa para reprodutibilidade estrita
SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# Configurações de exibição do Pandas para facilitar a análise das colunas unificadas
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)

# URL Base do GitHub em formato RAW para leitura direta via Pandas das tabelas da pasta /data
GITHUB_RAW_URL = "https://raw.githubusercontent.com/rgomesa2025/MVP_MACHINE_LEARNING_E_ANALYTICS/main/data/"

# Implementação matemática da função WAPE/WMAPE para o ecossistema Scikit-Learn
def wape_score(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    total_actual = np.sum(y_true)
    if total_actual == 0:
        return 0.0
    return np.sum(np.abs(y_true - y_pred)) / total_actual

# Criando o scorer oficial para usar no RandomizedSearchCV
wape_scorer = make_scorer(wape_score, greater_is_better=False)

# Confirmação do ambiente de execução
print(f"Python: {sys.version.split()[0]}")
print(f"Pandas: {pd.__version__}")
print(f"NumPy: {np.__version__}")
print(f"Scikit-learn: {sklearn.__version__}")
print(f"Ambiente configurado para leitura direta do GitHub.")
print(f"Semente Global (Seed) configurada: {SEED}")

Python: 3.12.13
Pandas: 2.2.2
NumPy: 2.0.2
Scikit-learn: 1.6.1
Ambiente configurado para leitura direta do GitHub.
Semente Global (Seed) configurada: 42

## 2.1 Dependências adicionais

Para a execução deste MVP, é necessária a instalação de pacotes complementares ao ecossistema padrão do Python. Embora as bibliotecas de manipulação de dados e regressão linear básica (como Pandas e Scikit-Learn) já sejam nativas em ambientes de ciência de dados, a modelagem preditiva das 5 curvas de hidrocarbonetos exige algoritmos avançados de Boosting.

Portanto, o projeto faz uso das seguintes dependências externas para garantir o treinamento dos modelos candidatos e a qualidade visual dos gráficos de projeção:

In [ ]:
#python
# Executar a linha abaixo caso o ambiente não possua os pacotes instalados:
!pip install -q xgboost lightgbm seaborn

## 2.2 Funções auxiliares

Para garantir a organização do pipeline e evitar a repetição de código durante a fase de modelagem, foram desenvolvidas funções específicas para a avaliação do desempenho preditivo das curvas. Como o MVP lida com um problema de regressão temporal multivariada, as funções calculam os erros volumétricos com base nas quatro principais métricas de aderência do mercado de energia: MAE, RMSE, R² e o MAPE (que quantifica o percentual médio de erro diretamente no negócio).

O bloco abaixo centraliza essas funções para que possam ser chamadas de forma limpa na validação do modelo baseline e dos modelos candidatos:

In [ ]:
#python
def calculate_mape(y_true, y_pred):
    """
    Calcula o Erro Percentual Absoluto Médio (MAPE).
    Remove valores nulos ou zerados do histórico para evitar divisões por zero.
    """
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    mask = y_true != 0
    if not np.any(mask):
        return np.nan
    return np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100


def evaluate_regression(y_true, y_pred):
    """
    Centraliza o cálculo das métricas de sucesso estabelecidas para as 5 curvas
    (Óleo, Condensado, Gás Natural, Gás Associado e Não Associado).
    """
    mse = mean_squared_error(y_true, y_pred)
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "RMSE": np.sqrt(mse),
        "MAPE (%)": calculate_mape(y_true, y_pred),
        "R2": r2_score(y_true, y_pred)
    }


def show_results_table(results_dict):
    """
    Consolida as métricas dos experimentos em um DataFrame do Pandas,
    permitindo a comparação direta entre o modelo baseline e os algoritmos de Machine Learning.
    """
    return pd.DataFrame(results_dict).T

# 3. Seleção e carga dos dados

Esta seção detalha a origem dos dados públicos utilizados no MVP, as justificativas para a escolha da base, os aspectos regulatórios envolvidos e a implementação do pipeline de extração automatizada das informações a partir do repositório do projeto.

### 3.1 Fonte dos dados

* **Nome do dataset:** Dados de Produção de Petróleo e Gás Natural.
* **Link da fonte:** [Produção de Petróleo e gás natural (ANP)](https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-estatisticos) / [Produção por Poços](https://cdp.anp.gov.br/ords/r/cdp_apex/consulta-dados-publicos-cdp/consulta-produ%C3%A7%C3%A3o-por-po%C3%A7o).
* **Por que este dataset foi escolhido:** O conjunto de dados concentra o histórico oficial, consolidado e auditado da produção nacional de hidrocarbonetos. Ele fornece, com granularidade ideal, o comportamento volumétrico real e desagregado das cinco curvas que compõem o escopo preditivo deste MVP, servindo como base sólida para o treinamento de algoritmos de séries temporais de longo prazo.
* **Restrições e condições consideradas:** O recorte dos dados considera o histórico consolidado mensal para evitar ruídos de leituras diárias ou paradas operacionais momentâneas de curtíssimo prazo (como manutenções de poços de 24h ou 48h), focando estritamente na tendência macro de declínio e comportamento dos reservatórios para o horizonte de 5 anos. Para viabilizar o pipeline automatizado deste MVP, a série histórica foi organizada de forma cronológica e particionada em arquivos anuais dentro do repositório GitHub do projeto.
* **Ética, privacidade, confidencialidade e licença:** O dataset é classificado como **Dados Abertos Governamentais**, sob a licença *Creative Commons Attribution (CC BY)*. Por se tratar de dados de produção agregados por campos institucionais, não existem informações sensíveis de indivíduos, violações de privacidade ou quebras de confidencialidade comercial, respeitando integralmente os preceitos éticos e as diretrizes da LGPD (Lei Geral de Proteção de Dados).

### 3.2 Carga dos dados

O bloco abaixo automatiza a extração e a consolidação do histórico de dados de produção. Para respeitar a organização do repositório no GitHub, onde as tabelas públicas estão divididas em pastas anuais e particionadas em arquivos mensais utilizando a nomenclatura padrão `ANO_MES_producao_Mar.csv` (onde "Mar" identifica o ambiente de produção offshore), o script realiza uma varredura cronológica gerando os índices dos meses de forma dinâmica e unifica todas as informações em um único DataFrame estruturado.

In [ ]:
# URL RAW correta do GitHub
base_url = "https://raw.githubusercontent.com/rgomesa2025/MVP_MACHINE_LEARNING_E_ANALYTICS/main/data"

# Anos disponíveis no projeto (2021 a 2025)
anos_producao = ["2021", "2022", "2023", "2024", "2025"]

# Meses de 01 a 12
meses_producao = [str(i).zfill(2) for i in range(1, 13)]

dfs_mensais = []
arquivos_lidos = 0
arquivos_com_erro = 0

print("=== Iniciando consolidação dos arquivos ===")

for ano in anos_producao:
    print(f"Processando ano {ano} ", end="", flush=True)

    for mes in meses_producao:
        nome_arquivo = f"{ano}_{mes}_producao_Mar.csv"
        url_completa = f"{base_url}/{ano}/{nome_arquivo}"

        try:
            # Estratégia de leitura adaptada para padrões da ANP (Vírgula vs Ponto e Vírgula / UTF-8 vs Latin-1)
            try:
                # 1ª Tentativa: Padrão internacional (Vírgula + UTF-8)
                df_mes = pd.read_csv(url_completa, encoding='utf-8')
            except Exception:
                try:
                    # 2ª Tentativa: Padrão nacional Excel (Ponto e vírgula + Latin-1 para os acentos)
                    df_mes = pd.read_csv(url_completa, sep=';', encoding='iso-8859-1')
                except Exception:
                    # 3ª Tentativa: Variação de exportação (Vírgula + Latin-1)
                    df_mes = pd.read_csv(url_completa, sep=',', encoding='iso-8859-1')

            # Criação das colunas de controle temporal para a modelagem de séries
            df_mes["ano_referencia"] = int(ano)
            df_mes["mes_referencia"] = int(mes)

            dfs_mensais.append(df_mes)
            arquivos_lidos += 1
            # Imprime um ponto para indicar progresso visual sem inundar a tela
            print(".", end="", flush=True)

        except Exception as e:
            arquivos_com_erro += 1
            print(f"\n   ✗ Erro ao ler {nome_arquivo} | Motivo: {e}")

    print(" ✓ Concluído!")

print("\n=== Resumo da carga ===")
print(f"Arquivos carregados com sucesso: {arquivos_lidos}")
print(f"Arquivos não localizados ou com erro: {arquivos_com_erro}")

# Consolidação final unificando todas as tabelas mensais
if len(dfs_mensais) > 0:
    df = pd.concat(dfs_mensais, ignore_index=True)
    print("\n=== Consolidação concluída ===")
    print(f"Linhas totais no DataFrame: {df.shape[0]}")
    print(f"Colunas totais no DataFrame: {df.shape[1]}")
    print("\nPrimeiras linhas do dataset consolidado:")

    # Renderiza as linhas do DataFrame no formato de tabela visual HTML
    display(df.head())
else:
    print("\n[ERRO CRÍTICO] Nenhum arquivo foi carregado. Verifique a integridade dos dados no GitHub.")

=== Iniciando consolidação dos arquivos ===
Processando ano 2021 ............ ✓ Concluído!
Processando ano 2022 ............ ✓ Concluído!
Processando ano 2023 ............ ✓ Concluído!
Processando ano 2024 ............ ✓ Concluído!
Processando ano 2025 ............ ✓ Concluído!

=== Resumo da carga ===
Arquivos carregados com sucesso: 60
Arquivos não localizados ou com erro: 0

=== Consolidação concluída ===
Linhas totais no DataFrame: 61974
Colunas totais no DataFrame: 50

Primeiras linhas do dataset consolidado:

,Estado,Bacia,Nome Poço ANP,Nome Poço Operador,Campo,Operador,Número do Contrato,Período,Óleo (bbl/dia),Condensado (bbl/dia),...,% em Volumes Undecanos,% em Volumes Oxigênio,% em Volumes Nitrogênio,% em Volumes Gás Carbônico,Densidade GLP Gás,Densidade GLP Líquido,PCS GP(kJ/m³),Data de atualização,ano_referencia,mes_referencia
0,Rio de Janeiro,Santos,1-BRSA-976-RJS,1RJS691,SÉPIA,Petrobras,48610012913201005,2021/01,0,0,...,0,0,",60417","24,67724","2,03995","532,80966","29851,5187",09/06/2026,2021,1
1,Rio de Janeiro,Santos,3-BRSA-1201-RJS,3RJS721,SÉPIA,Petrobras,48610012913201005,2021/01,0,0,...,0,0,",60417","24,67724","2,03995","532,80966","29851,5187",09/06/2026,2021,1
2,Rio de Janeiro,Santos,9-BRSA-1254-RJS,9RJS733,SÉPIA,Petrobras,48610012913201005,2021/01,0,0,...,0,0,",60417","24,67724","2,03995","532,80966","29851,5187",09/06/2026,2021,1
3,Rio de Janeiro,Santos,9-SEP-1-RJS,9SEP1RJS,SÉPIA,Petrobras,48610012913201005,2021/01,0,0,...,0,0,",60417","24,67724","2,03995","532,80966","29851,5187",09/06/2026,2021,1
4,São Paulo,Santos,3-BRSA-788-SPS,3SPS69,SAPINHOÁ,Petrobras,486100038842000,2021/01,"19956,4647",0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09/06/2026,2021,1

### 3.3 Visão geral do dataset

Antes de iniciar as transformações e a modelagem preditiva, esta subseção estabelece um diagnóstico estrutural completo do conjunto de dados unificado. A análise compreende o mapeamento volumétrico, a integridade das observações e a identificação do papel de cada variável dentro do pipeline de Machine Learning.

#### Análise Estrutural e Integridade dos Dados

O bloco de código abaixo executa a varredura técnica do DataFrame consolidado para extrair as propriedades fundamentais da base que são:

*   quantidade de linhas e colunas;
*   tipos dos atributos;
*   valores ausentes;
*   duplicatas;
*   colunas que não devem entrar no modelo;
*   descrição do target.

**Quantidade de Linhas e Colunas**

Este bloco extrai a volumetria total da base unificada (2021 a 2025).

In [ ]:
#python
# Verificação das dimensões do DataFrame
linhas, colunas = df.shape

print("=== Volumetria do Dataset ===")
print(f"Total de Registros (Linhas): {linhas}")
print(f"Total de Atributos (Colunas): {colunas}")

=== Volumetria do Dataset ===
Total de Registros (Linhas): 61974
Total de Atributos (Colunas): 50

**Tipos dos Atributos**

Validação da tipagem de cada coluna para garantir que variáveis numéricas (volumes) e temporais estejam nos formatos corretos antes do pré-processamento.

In [ ]:
#python

print("Formato do dataset:", df.shape)
print("\n=== Tipagem dos Atributos ===")
# Converte a série de tipos em um DataFrame com a coluna 'Tipo de Dado'
df_tipos = df.dtypes.to_frame(name="Tipo de Dado")

# Define o nome do índice
df_tipos.index.name = "Nome da Coluna"

# Transforma o índice em uma coluna comum para garantir a exibição dos títulos na tabela
df_tipos_visual = df_tipos.reset_index()

# Renderiza no formato visual de tabela HTML com os títulos explícitos
display(df_tipos_visual)


print("\n=== Resumo por Tipo de Dado ===")
# Converte o resumo numérico em um DataFrame com a coluna 'Quantidade de Colunas'
df_resumo = df.dtypes.value_counts().to_frame(name="Quantidade de Colunas")

# Define o nome do índice do resumo
df_resumo.index.name = "Tipo de Dado"

# Transforma o índice em uma coluna comum para o resumo
df_resumo_visual = df_resumo.reset_index()

# Renderiza a tabela de resumo formatada
display(df_resumo_visual)

Formato do dataset: (61974, 50)

=== Tipagem dos Atributos ===

                    Nome da Coluna Tipo de Dado
0                           Estado       object
1                            Bacia       object
2                    Nome Poço ANP       object
3               Nome Poço Operador       object
4                            Campo       object
5                         Operador       object
6               Número do Contrato       object
7                          Período       object
8                   Óleo (bbl/dia)       object
9             Condensado (bbl/dia)       object
10              Petróleo (bbl/dia)       object
11     Gás Natural (Mm³/dia) Assoc       object
12   Gás Natural (Mm³/dia) N Assoc       object
13     Gás Natural (Mm³/dia) Total       object
14   Volume Gás Royalties (m³/mês)       object
15                  Água (bbl/dia)       object
16              Instalação Destino       object
17                 Tipo Instalação       object
18  Tempo de Produção (hs por mês)        int64
19                Período da Carga       object
20                        Corrente       object
21                        Grau API       object
22   Fração de Destilados|Lev|Cort       object
23    Fração de Destilados|Lev|Vol       object
24  Fração de Destilados|Méd|Corte       object
25    Fração de Destilados|Méd|Vol       object
26  Fração de Destilados|Pes|Corte       object
27    Fração de Destilados|Pes|Vol       object
28             % em Volumes Metano       object
29              % em Volumes Etano       object
30            % em Volumes Propano       object
31         % em Volumes Iso-Butano       object
32             % em Volumes Butano       object
33        % em Volumes Iso-Pentano       object
34          % em Volumes n-Pentano       object
35            % em Volumes Hexanos       object
36           % em Volumes Heptanos       object
37            % em Volumes Octanos       object
38            % em Volumes Nonanos       object
39            % em Volumes Decanos       object
40          % em Volumes Undecanos       object
41           % em Volumes Oxigênio       object
42         % em Volumes Nitrogênio       object
43      % em Volumes Gás Carbônico       object
44               Densidade GLP Gás       object
45           Densidade GLP Líquido       object
46                   PCS GP(kJ/m³)       object
47             Data de atualização       object
48                  ano_referencia        int64
49                  mes_referencia        int64

=== Resumo por Tipo de Dado ===

  Tipo de Dado  Quantidade de Colunas
0       object                     47
1        int64                      3

**Valores Ausentes**

Mapeamento de dados nulos na base. Identificar lacunas ajuda a planejar a estratégia de imputação para poços ou meses sem registros.

In [ ]:
#python
print("=== Análise de Valores Ausentes (Nulos) ===")
total_nulos = df.isnull().sum()

# Peso percentual calculado dividindo os nulos da coluna pelo total de linhas da base (e não pela coluna vizinha)
proporcao_nulos = (df.isnull().sum() / len(df)) * 100

# Consolida em um DataFrame com nomenclaturas claras para o negócio
df_nulos = pd.DataFrame({
    'Total Nulos': total_nulos,
    'Proporção de Nulos (%)': proporcao_nulos.round(2)
})

# Define o nome do índice (que guarda os nomes das colunas originais)
df_nulos.index.name = "Nome da Coluna"

# Transforma o índice em uma coluna comum para garantir a exibição do título na tabela
df_nulos_visual = df_nulos.reset_index()

# Filtra para exibir apenas as colunas que possuem alguma ausência (Total Nulos > 0)
colunas_com_nulos = df_nulos_visual[df_nulos_visual['Total Nulos'] > 0]

if not colunas_com_nulos.empty:
    # Renderiza no formato visual de tabela HTML com as colunas: Nome da Coluna | Total Nulos | Proporção de Nulos (%)
    display(colunas_com_nulos)
else:
    print("Sucesso: Nenhum valor ausente encontrado no dataset consolidado!")

=== Análise de Valores Ausentes (Nulos) ===

                    Nome da Coluna  Total Nulos  Proporção de Nulos (%)
16              Instalação Destino        10491                   16.93
17                 Tipo Instalação        10491                   16.93
19                Período da Carga         7974                   12.87
20                        Corrente         7974                   12.87
21                        Grau API         7974                   12.87
24  Fração de Destilados|Méd|Corte         7974                   12.87
28             % em Volumes Metano         7616                   12.29
29              % em Volumes Etano         7616                   12.29
30            % em Volumes Propano         7616                   12.29
31         % em Volumes Iso-Butano         7616                   12.29
32             % em Volumes Butano         7616                   12.29
33        % em Volumes Iso-Pentano         7616                   12.29
34          % em Volumes n-Pentano         7616                   12.29
35            % em Volumes Hexanos         7616                   12.29
36           % em Volumes Heptanos         7616                   12.29
37            % em Volumes Octanos         7616                   12.29
38            % em Volumes Nonanos         7616                   12.29
39            % em Volumes Decanos         7616                   12.29
40          % em Volumes Undecanos         7616                   12.29
41           % em Volumes Oxigênio         7616                   12.29
42         % em Volumes Nitrogênio         7616                   12.29
43      % em Volumes Gás Carbônico         7616                   12.29
44               Densidade GLP Gás         7616                   12.29
45           Densidade GLP Líquido         7616                   12.29
46                   PCS GP(kJ/m³)         7616                   12.29

**Detecção de Duplicatas**

Garante a integridade estatística removendo ou validando linhas idênticas que possam enviesar o aprendizado do modelo.

In [ ]:
# Contagem de linhas duplicadas no histórico completo
print("=== Verificação de Linhas Duplicadas ===")
total_duplicadas = df.duplicated().sum()

print(f"Quantidade de linhas 100% duplicadas encontradas: {total_duplicadas}")

# Caso existam duplicatas, exibe as 3 primeiras para auditoria visual
if total_duplicadas > 0:
    print("\nExemplo de registros duplicados:")
    display(df[df.duplicated(keep=False)].head(3))

=== Verificação de Linhas Duplicadas ===
Quantidade de linhas 100% duplicadas encontradas: 0

**Colunas removidas do modelo**

Este bloco isola as colunas excluídas do modelo de Machine Learning. Os descartes evitam ruídos textuais de dados cadastrais da ANP, impedem regras falsas de tempo geradas pelos índices da carga e eliminam volumes secundários redundantes. A triagem garante a consistência matemática exata: 11 colunas utilizadas mais 39 excluídas fecham perfeitamente as 50 colunas totais da base.

In [ ]:

# Lista exata das 11 colunas que você escolheu utilizar no MVP
colunas_utilizadas = [
    'Período', 'Estado', 'Bacia', 'Nome Poço Operador', 'Campo', 'Operador',
    'Óleo (bbl/dia)', 'Condensado (bbl/dia)',
    'Gás Natural (Mm³/dia) Assoc', 'Gás Natural (Mm³/dia) N Assoc',
    'Gás Natural (Mm³/dia) Total'
]

lista_exclusao = []

# Varre todas as colunas do dataset completo
for coluna in df.columns:
    # Se a coluna NÃO está na sua lista de 11 colunas, ela vai direto para a lista de exclusão
    if coluna not in colunas_utilizadas:
        # Identifica se é uma das colunas de controle criadas no pipeline para dar uma justificativa clara
        if coluna in ['ano_referencia', 'mes_referencia']:
            justificativa = "Índice de controle temporal criado no pipeline de carga. Não entra no modelo."
        else:
            justificativa = "Metadado administrativo ou variável cadastral não preditiva para as curvas."

        lista_exclusao.append({
            'Nome da Coluna': coluna,
            'Tipo de Dado': str(df[coluna].dtype),
            'Status no MVP': 'Excluída do Treinamento',
            'Justificativa': justificativa
        })

# Transforma a lista de descartadas em um DataFrame para exibição tabular
df_excluidas = pd.DataFrame(lista_exclusao)

print("=== Balanço Volumétrico de Colunas ===")
print(f"Total de colunas no Dataset original: {df.shape[1]}")
print(f"  (+) Colunas utilizadas no MVP: {len(colunas_utilizadas)}")
print(f"  (+) Colunas excluídas listadas abaixo: {df_excluidas.shape[0]}")
print("-" * 40)

if not df_excluidas.empty:
    # Renderiza a tabela HTML mostrando apenas as colunas que ficaram de fora
    display(df_excluidas)
else:
    print("Todas as colunas do dataset estão mapeadas na lista de uso.")

=== Balanço Volumétrico de Colunas ===
Total de colunas no Dataset original: 50
  (+) Colunas utilizadas no MVP: 11
  (+) Colunas excluídas listadas abaixo: 39
----------------------------------------

,Nome da Coluna,Tipo de Dado,Status no MVP,Justificativa
0,Nome Poço ANP,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
1,Número do Contrato,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
2,Petróleo (bbl/dia),object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
3,Volume Gás Royalties (m³/mês),object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
4,Água (bbl/dia),object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
5,Instalação Destino,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
6,Tipo Instalação,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
7,Tempo de Produção (hs por mês),int64,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
8,Período da Carga,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
9,Corrente,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
10,Grau API,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
11,Fração de Destilados|Lev|Cort,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
12,Fração de Destilados|Lev|Vol,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
13,Fração de Destilados|Méd|Corte,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
14,Fração de Destilados|Méd|Vol,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
15,Fração de Destilados|Pes|Corte,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
16,Fração de Destilados|Pes|Vol,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
17,% em Volumes Metano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
18,% em Volumes Etano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
19,% em Volumes Propano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
20,% em Volumes Iso-Butano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
21,% em Volumes Butano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
22,% em Volumes Iso-Pentano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
23,% em Volumes n-Pentano,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
24,% em Volumes Hexanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
25,% em Volumes Heptanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
26,% em Volumes Octanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
27,% em Volumes Nonanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
28,% em Volumes Decanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
29,% em Volumes Undecanos,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
30,% em Volumes Oxigênio,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
31,% em Volumes Nitrogênio,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
32,% em Volumes Gás Carbônico,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
33,Densidade GLP Gás,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
34,Densidade GLP Líquido,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
35,PCS GP(kJ/m³),object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
36,Data de atualização,object,Excluída do Treinamento,Metadado administrativo ou variável cadastral ...
37,ano_referencia,int64,Excluída do Treinamento,Índice de controle temporal criado no pipeline...
38,mes_referencia,int64,Excluída do Treinamento,Índice de controle temporal criado no pipeline...

**Descrição do target**

Este bloco isola e analisa estatisticamente as 5 curvas de produção de longo prazo que servem como os targets (variáveis alvo): **óleo, óleo condensado, gás natural, gás associado e gás não associado**. Por se tratar de uma regressão multivariada baseada no histórico público, o modelo usará estes dados para projetar o comportamento das curvas por um horizonte de 5 anos. A análise descritiva dessas variáveis estabelece a base para avaliar o desempenho dos algoritmos preditivos e compará-los contra a abordagem de referência.

In [ ]:
# Lista exata dos 5 targets (variáveis alvo) do MVP
targets_selecionados = [
    'Óleo (bbl/dia)',
    'Condensado (bbl/dia)',
    'Gás Natural (Mm³/dia) Assoc',
    'Gás Natural (Mm³/dia) N Assoc',
    'Gás Natural (Mm³/dia) Total'
]

print("=== Análise Descritiva dos Targets do Modelo ===")

# Verifica se todas as colunas estão presentes no DataFrame antes de calcular
targets_existentes = [col for col in targets_selecionados if col in df.columns]

if len(targets_existentes) == 5:
    # Gera a matriz estatística descritiva, arredonda para 2 casas decimais e transpõe para virar tabela
    df_estatistico = df[targets_existentes].describe().round(2)

    # Renomeia o índice para identificar as métricas estatísticas calculadas pelo pandas
    df_estatistico.index.name = "Métrica Estatística"

    # Reseta o índice para que "Métrica Estatística" vire o título visível da primeira coluna
    df_estatistico_visual = df_estatistico.reset_index()

    # Exibe a tabela rica formatada em HTML
    display(df_estatistico_visual)

else:
    print(f"[Aviso] Foram encontrados apenas {len(targets_existentes)} dos 5 alvos pretendidos.")
    print("Verifique se os nomes das colunas no seu GitHub estão idênticos aos da lista.")
    print(f"Colunas numéricas disponíveis no momento: {df.select_dtypes(include=['number']).columns.tolist()}")

=== Análise Descritiva dos Targets do Modelo ===

Nome da Coluna,Métrica Estatística,Óleo (bbl/dia),Condensado (bbl/dia),Gás Natural (Mm³/dia) Assoc,Gás Natural (Mm³/dia) N Assoc,Gás Natural (Mm³/dia) Total
0,count,61974,61974,61974,61974,61974
1,unique,44239,1316,41539,1105,42532
2,top,0,0,0,0,0
3,freq,17353,60658,17216,60870,16232

In [ ]:
#@title ### 3.4 Dicionário de dados

import pandas as pd
from IPython.display import display

# 1. Lista exata das colunas selecionadas para o MVP
colunas_usadas = [
    'Período', 'Estado', 'Bacia', 'Nome Poço Operador', 'Campo', 'Operador'
]

# 2. Lista exata dos alvos (targets) do MVP
targets_mvp = [
    'Óleo (bbl/dia)', 'Condensado (bbl/dia)',
    'Gás Natural (Mm³/dia) Assoc', 'Gás Natural (Mm³/dia) N Assoc',
    'Gás Natural (Mm³/dia) Total'
]

# Dicionário de mapeamento para colunas técnicas específicas da ANP
colunas_especificas_anp = {
    'grau api': ('numérica', 'Métrica de densidade do petróleo (Grau API).', 'Excluída; o foco do MVP é puramente na disposição volumétrica de longo prazo.'),
    'densidade': ('numérica', 'Densidade relativa do hidrocarboneto.', 'Excluída; parâmetro físico-químico fora do escopo de regressão das curvas.'),
    'pcs': ('numérica', 'Poder Calorífico Superior do gás natural.', 'Excluída; métrica de potencial energético não utilizada no modelo preditivo.'),
    'percentual': ('numérica', 'Indicador de peso percentual ou fração de distribuição.', 'Excluída do treinamento para evitar ruído e focar nos volumes absolutos.'),
    'porcentagem': ('numérica', 'Indicador percentual de componentes ou frações.', 'Excluída do treinamento para evitar ruído e focar nos volumes absolutos.')
}

dicionario_dados = []

# 3. Varre todas as colunas do dataset bruto (50 colunas)
for coluna in df.columns:
    coluna_minuscula = coluna.lower()

    # --- ESTRATÉGIA DE TIPAGEM E DOCUMENTAÇÃO ---
    if coluna in targets_mvp:
        tipo_negocio = "alvo (numérica)"
        desc_map = f"Volume diário de {coluna.split(' (')[0]} movimentado."
        obs_map = "Valor previsto: curva contínua projetada para o horizonte de 5 anos."
        sera_usada = "alvo"

    elif coluna in colunas_usadas:
        sera_usada = "sim"
        obs_map = "Mantida como feature preditiva ou guia de série temporal no MVP."
        if "object" in str(df[coluna].dtype) and coluna != 'Período':
            tipo_negocio = "categórica"
            desc_map = f"Variável categórica de especificação geográfica ou operacional ({coluna})."
        else:
            tipo_negocio = "data"
            desc_map = "Identificador cronológico (mês/ano) do registro de produção."

    elif "corte" in coluna_minuscula:
        tipo_negocio = "categórica"
        desc_map = f"Faixa descritiva ou intervalo de corte de destilados ({coluna})."
        obs_map = "Excluída; informação textual de processo industrial fora do escopo de volumes brutos."
        sera_usada = "não"

    elif "fração" in coluna_minuscula or "fracao" in coluna_minuscula:
        tipo_negocio = "numérica"
        desc_map = f"Fração volumétrica ou composição de destilados ({coluna})."
        obs_map = "Excluída; parâmetro de refino/fração que não entra na modelagem das curvas brutas."
        sera_usada = "não"

    elif "%" in coluna:
        tipo_negocio = "numérica"
        desc_map = f"Fração percentual de composição técnica ({coluna})."
        obs_map = "Excluída do treinamento para manter o foco estritamente nos volumes absolutos."
        sera_usada = "não"

    elif "data" in coluna_minuscula or "período da carga" in coluna_minuscula or "periodo da carga" in coluna_minuscula:
        tipo_negocio = "data"
        desc_map = f"Metadado temporal de controle ou auditoria do sistema ({coluna})."
        obs_map = "Excluída; não possui valor preditivo para comportamento de reservatório."
        sera_usada = "não"

    elif any(termo in coluna_minuscula for termo in ["volume", "água", "agua", "petróleo", "petroleo"]):
        tipo_negocio = "numérica"
        desc_map = f"Métrica volumétrica operacional ou de fluidos secundários ({coluna})."
        obs_map = "Excluída; variável fora do escopo das 5 curvas principais selecionadas."
        sera_usada = "não"

    elif any(termo in coluna_minuscula for termo in colunas_especificas_anp.keys()):
        termo_encontrado = [t for t in colunas_especificas_anp.keys() if t in coluna_minuscula][0]
        tipo_negocio, desc_map, obs_map = colunas_especificas_anp[termo_encontrado]
        sera_usada = "não"

    else:
        sera_usada = "não"
        tipo_real = str(df[coluna].dtype)

        if coluna in ['ano_referencia', 'mes_referencia']:
            tipo_negocio = "numérica"
            desc_map = "Índice de controle temporal criado no pipeline de carga."
            obs_map = "Excluída; o tempo será gerenciado via TimeSeriesSplit."
        elif "object" in tipo_real:
            tipo_negocio = "categórica"
            desc_map = f"Metadado administrativo ou cadastral ({coluna})."
            obs_map = "Excluída do treinamento para evitar ruído e alta cardinalidade."
        else:
            tipo_negocio = "numérica"
            desc_map = f"Métrica numérica ou operacional residual ({coluna})."
            obs_map = "Excluída do treinamento por não fazer parte do escopo principal."

    dicionario_dados.append({
        'Coluna': coluna,
        'Tipo': tipo_negocio,
        'Descrição': desc_map,
        'Será usada no modelo?': sera_usada,
        'Observações': obs_map
    })

df_dicionario = pd.DataFrame(dicionario_dados)

# Renderiza diretamente a tabela limpa
display(df_dicionario)

,Coluna,Tipo,Descrição,Será usada no modelo?,Observações
0,Estado,categórica,Variável categórica de especificação geográfic...,sim,Mantida como feature preditiva ou guia de séri...
1,Bacia,categórica,Variável categórica de especificação geográfic...,sim,Mantida como feature preditiva ou guia de séri...
2,Nome Poço ANP,categórica,Metadado administrativo ou cadastral (Nome Poç...,não,Excluída do treinamento para evitar ruído e al...
3,Nome Poço Operador,categórica,Variável categórica de especificação geográfic...,sim,Mantida como feature preditiva ou guia de séri...
4,Campo,categórica,Variável categórica de especificação geográfic...,sim,Mantida como feature preditiva ou guia de séri...
5,Operador,categórica,Variável categórica de especificação geográfic...,sim,Mantida como feature preditiva ou guia de séri...
6,Número do Contrato,categórica,Metadado administrativo ou cadastral (Número d...,não,Excluída do treinamento para evitar ruído e al...
7,Período,data,Identificador cronológico (mês/ano) do registr...,sim,Mantida como feature preditiva ou guia de séri...
8,Óleo (bbl/dia),alvo (numérica),Volume diário de Óleo movimentado.,alvo,Valor previsto: curva contínua projetada para ...
9,Condensado (bbl/dia),alvo (numérica),Volume diário de Condensado movimentado.,alvo,Valor previsto: curva contínua projetada para ...
10,Petróleo (bbl/dia),numérica,Métrica volumétrica operacional ou de fluidos ...,não,Excluída; variável fora do escopo das 5 curvas...
11,Gás Natural (Mm³/dia) Assoc,alvo (numérica),Volume diário de Gás Natural movimentado.,alvo,Valor previsto: curva contínua projetada para ...
12,Gás Natural (Mm³/dia) N Assoc,alvo (numérica),Volume diário de Gás Natural movimentado.,alvo,Valor previsto: curva contínua projetada para ...
13,Gás Natural (Mm³/dia) Total,alvo (numérica),Volume diário de Gás Natural movimentado.,alvo,Valor previsto: curva contínua projetada para ...
14,Volume Gás Royalties (m³/mês),numérica,Métrica volumétrica operacional ou de fluidos ...,não,Excluída; variável fora do escopo das 5 curvas...
15,Água (bbl/dia),numérica,Métrica volumétrica operacional ou de fluidos ...,não,Excluída; variável fora do escopo das 5 curvas...
16,Instalação Destino,categórica,Metadado administrativo ou cadastral (Instalaç...,não,Excluída do treinamento para evitar ruído e al...
17,Tipo Instalação,categórica,Metadado administrativo ou cadastral (Tipo Ins...,não,Excluída do treinamento para evitar ruído e al...
18,Tempo de Produção (hs por mês),numérica,Métrica numérica ou operacional residual (Temp...,não,Excluída do treinamento por não fazer parte do...
19,Período da Carga,data,Metadado temporal de controle ou auditoria do ...,não,Excluída; não possui valor preditivo para comp...
20,Corrente,categórica,Metadado administrativo ou cadastral (Corrente).,não,Excluída do treinamento para evitar ruído e al...
21,Grau API,numérica,Métrica de densidade do petróleo (Grau API).,não,Excluída; o foco do MVP é puramente na disposi...
22,Fração de Destilados|Lev|Cort,numérica,Fração volumétrica ou composição de destilados...,não,Excluída; parâmetro de refino/fração que não e...
23,Fração de Destilados|Lev|Vol,numérica,Fração volumétrica ou composição de destilados...,não,Excluída; parâmetro de refino/fração que não e...
24,Fração de Destilados|Méd|Corte,categórica,Faixa descritiva ou intervalo de corte de dest...,não,Excluída; informação textual de processo indus...
25,Fração de Destilados|Méd|Vol,numérica,Fração volumétrica ou composição de destilados...,não,Excluída; parâmetro de refino/fração que não e...
26,Fração de Destilados|Pes|Corte,categórica,Faixa descritiva ou intervalo de corte de dest...,não,Excluída; informação textual de processo indus...
27,Fração de Destilados|Pes|Vol,numérica,Fração volumétrica ou composição de destilados...,não,Excluída; parâmetro de refino/fração que não e...
28,% em Volumes Metano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
29,% em Volumes Etano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
30,% em Volumes Propano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
31,% em Volumes Iso-Butano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
32,% em Volumes Butano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
33,% em Volumes Iso-Pentano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
34,% em Volumes n-Pentano,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
35,% em Volumes Hexanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
36,% em Volumes Heptanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
37,% em Volumes Octanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
38,% em Volumes Nonanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
39,% em Volumes Decanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
40,% em Volumes Undecanos,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
41,% em Volumes Oxigênio,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
42,% em Volumes Nitrogênio,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
43,% em Volumes Gás Carbônico,numérica,Fração percentual de composição técnica (% em ...,não,Excluída do treinamento para manter o foco est...
44,Densidade GLP Gás,numérica,Densidade relativa do hidrocarboneto.,não,Excluída; parâmetro físico-químico fora do esc...
45,Densidade GLP Líquido,numérica,Densidade relativa do hidrocarboneto.,não,Excluída; parâmetro físico-químico fora do esc...
46,PCS GP(kJ/m³),numérica,Poder Calorífico Superior do gás natural.,não,Excluída; métrica de potencial energético não ...
47,Data de atualização,data,Metadado temporal de controle ou auditoria do ...,não,Excluída; não possui valor preditivo para comp...
48,ano_referencia,numérica,Índice de controle temporal criado no pipeline...,não,Excluída; o tempo será gerenciado via TimeSeri...
49,mes_referencia,numérica,Índice de controle temporal criado no pipeline...,não,Excluída; o tempo será gerenciado via TimeSeri...